Repository OS-Sketch/www.os-sketch.com, pull requests merged in 2022-09, with the labels that each got.

#12 Update the Course Syllabus and Polish the Learning Community Content
  README.md
  docs/operating-systems/learning-community.md
  docs/operating-systems/syllabus.md
  overrides/partials/source-file.html
Labels: documentation

#20 Delete unnecessary files and add to .gitignore
  .DS_Store
  .gitignore
  .vscode/settings.json
Labels: documentation, enhancement

#18 Remove the use of Google Analytics in the mkdocs.yml file
  mkdocs.yml
Labels: bug

#23 Final draft of learning objective
  docs/operating-systems/learning-objectives.md
Labels: documentation

#31 Updates the slides for systems introduction, including the new diagram
  decks/os-slides/systems-introduction/public/os-sketch-process.svg
  decks/os-slides/systems-introduction/slides.md
Labels: documentation, enhancement

#33 Add slide content about the API chapters and the direct execution content
  decks/os-slides/package.json
  decks/os-slides/process-execution/.npmrc
  decks/os-slides/process-execution/README.md
  decks/os-slides/process-execution/components/Counter.vue
  decks/os-slides/process-execution/package.json
  decks/os-slides/process-execution/public/os-sketch-systems-introduction.svg
  decks/os-slides/process-execution/setup/windicss.ts
  decks/os-slides/process-execution/slides.md
  decks/os-slides/process-execution/styles/base.css
  decks/os-slides/process-execution/styles/code.css
  decks/os-slides/process-execution/styles/index.ts
  decks/os-slides/process-execution/styles/layouts.css
  decks/os-slides/systems-introduction/slides.md
  docs/img/os-sketch-systems-introduction-inverted.svg
  docs/operating-systems/schedule.md
  docs/operating-systems/sketches.md
  mkdocs.yml
Labels: enhancement
